### ISSUE TITLE
depends.txt is deprecated, undeclared global in init.lua

### ISSUE THREAD

**Issue by berengma** [ZenonSeth/treasure_chest#1]
```
debug2023-10-21.log:2023-10-21 10:25:19: WARNING[Server]: Assignment to undeclared global "diff" inside a function at /home/mars/.minetest/mods/treasure_chest/init.lua:112
```
easy to solve I guess :)

**Comment by ZenonSeth** [comment]
Yeah, this mod is pretty old at this point. But thanks for reporting this, I'll have a look and fix it up.

**Comment by berengma** [comment]
Old but good, I still have it on two of my servers running :) If you prefer a PR just tell me.

**Comment by ZenonSeth** [comment]
Glad to hear it's still being useful! I'm happy to accept PRs, but in this case I already fixed this, and various other things that were out of date (most importantly namespacing all those global functions I had used)

New release is now available: https://github.com/ZenonSeth/treasure_chest/releases/tag/1.1 - also should be up on ContentDB soon

**Comment by berengma** [comment]
Thanks, all servers updates :)
